[build]
publish = "/"

#command = "yarn start"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[context.production]
publish = "/"
#command = "yarn && yarn start"
environment = { NODE_VERSION = "16.14.2" }

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "frame-ancestors https://www.facebook.com"

cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''
